/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package satcks_and_queues;

public class App {

    public static void main(String[] args) {
//       Stack stack = new Stack();
//       stack.push(5);
//       stack.push(10);
//       stack.push(20);
//       stack.push(-7);
//      System.out.println(stack);
//      stack.pop();
//      System.out.println(stack);
      Queue queue = new Queue();
      queue.enqueue(10);
      queue.enqueue(15);
      queue.enqueue(7);
      queue.enqueue(0);
      System.out.println(queue.peek());
//      queue.dequeue();
//      queue.dequeue();
//      queue.dequeue();
//      queue.dequeue();
      System.out.println(queue);
    }
}
