/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codes.app.src.main.stacksandqueues;

public class App {

    public static void main(String[] args) {
      Stack s1 = new Stack();
//      s1.push(100);
//      s1.push(20);
//      s1.push(4);
//      s1.push(0);
//      s1.push(50);
//      s1.push(10);
//      s1.push(99);
//      s1.pop();
//      s1.pop();
//      s1.pop();
      System.out.println("max is: " + s1.maxStack.peek());
      System.out.println("---------------");
      System.out.println(s1);
      System.out.println("---------------");
      System.out.println(s1.maxStack);
    }
}
