/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codes.app.src.main.stacksandqueues;

public class App {

    public static void main(String[] args) {
      PseudoQueue queue = new PseudoQueue();
      queue.enqueue(10);
      queue.enqueue(15);
      queue.enqueue(20);
//      System.out.println(queue.dequeue());
      System.out.println(queue);
      queue.dequeue();
      System.out.println(queue);
      queue.dequeue();
      System.out.println(queue);
      queue.dequeue();
      System.out.println(queue);
    }
}
